services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/noah/jellyfin/config:/config
      - /home/noah/jellyfin/cache:/cache
      - /home/noah/media:/media
      - type: bind
        source: /home/noah/media
        target: /media
      - type: bind
        source: /home/noah/media2
        target: /media2
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
      # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'